<a href="https://colab.research.google.com/github/prpawan03/marvel-lvl1/blob/main/task1/linear%20regression/bengaluru.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [ ]:
from google.colab import files
files.upload()

!pip install -q kaggle

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

! kaggle datasets download amitabhajoy/bengaluru-house-price-data

Saving kaggle.json to kaggle (1).json
bengaluru-house-price-data.zip: Skipping, found more recently modified local copy (use --force to force download)

In [ ]:
!unzip bengaluru-house-price-data.zip

unzip:  cannot find or open bengaluru-house-price-data.zip, bengaluru-house-price-data.zip.zip or bengaluru-house-price-data.zip.ZIP.

In [ ]:
df = pd.read_csv('/content/Bengaluru_House_Data.csv')
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [ ]:
df.drop(['availability','society','area_type'],axis ="columns",inplace =True)

In [ ]:
df.isnull().sum()

#drop null value
df.dropna(inplace=True)

df.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
balcony       0
price         0
dtype: int64

In [ ]:
df["bhk"] = df["size"].apply(lambda x: int(x.split(' ')[0]))
df

,location,size,total_sqft,bath,balcony,price,bhk
0,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07,2
1,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00,4
2,Uttarahalli,3 BHK,1440,2.0,3.0,62.00,3
3,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00,3
4,Kothanur,2 BHK,1200,2.0,1.0,51.00,2
...,...,...,...,...,...,...,...
13314,Green Glen Layout,3 BHK,1715,3.0,3.0,112.00,3
13315,Whitefield,5 Bedroom,3453,4.0,0.0,231.00,5
13317,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.00,2
13318,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.00,4
13319,Doddathoguru,1 BHK,550,1.0,1.0,17.00,1

In [ ]:
df.total_sqft.unique()

#function for filterized range value
def is_float(x):
    try:
        float(x)
    except:
        return False
    return True

#range value
df[df["total_sqft"].apply(is_float) == False]

#Range to average value
def converter(x):
    token = x.split("-")
    if len(token) == 2:
        x = (float(token[0]) + float(token[1]))/2
    try:
        return float(x)
    except:
        return None

#convert range to 1 value
df["sqft"] = df.total_sqft.apply(converter)

In [ ]:
df["price_per_sqft"] = df.price*100000/df.sqft

In [ ]:
df.drop(["balcony", "total_sqft", "size", "price_per_sqft", "location"], axis="columns", inplace=True)
df

       bath   price  bhk    sqft
0       2.0   39.07    2  1056.0
1       5.0  120.00    4  2600.0
2       2.0   62.00    3  1440.0
3       3.0   95.00    3  1521.0
4       2.0   51.00    2  1200.0
...     ...     ...  ...     ...
13314   3.0  112.00    3  1715.0
13315   4.0  231.00    5  3453.0
13317   2.0   60.00    2  1141.0
13318   4.0  488.00    4  4689.0
13319   1.0   17.00    1   550.0

[12710 rows x 4 columns]

In [ ]:
X = df.drop("price", axis='columns')
y = df.price
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
df = df.dropna()

In [ ]:
model = linear_model.LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(X_test)
print(y_pred)

[132.065656    65.34624207 211.3191981  ... 187.40871264 120.89065017
  85.00359543]

In [ ]:
print(y_test)

721      100.00
5175      65.00
9149     241.00
4662     120.00
7588     289.00
          ...
5152     130.00
12832     67.75
6034     650.00
8223      70.00
5520      60.00
Name: price, Length: 4181, dtype: float64

In [ ]:
print(np.mean((y_pred-y_test)**2))

11336.79555557521